/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardYardRouteImport } from './routes/dashboard.yard'
import { Route as DashboardWeighbridgeRouteImport } from './routes/dashboard.weighbridge'
import { Route as DashboardTasksRouteImport } from './routes/dashboard.tasks'
import { Route as DashboardSelfRouteImport } from './routes/dashboard.self'
import { Route as DashboardOcrReviewRouteImport } from './routes/dashboard.ocr-review'
import { Route as DashboardGateRouteImport } from './routes/dashboard.gate'
import { Route as DashboardDockRouteImport } from './routes/dashboard.dock'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAiopsRouteImport } from './routes/dashboard.aiops'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as CheckoutTokenRouteImport } from './routes/checkout.$token'
import { Route as CheckinTokenRouteImport } from './routes/checkin.$token'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardYardRoute = DashboardYardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWeighbridgeRoute = DashboardWeighbridgeRouteImport.update({
  id: '/weighbridge',
  path: '/weighbridge',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSelfRoute = DashboardSelfRouteImport.update({
  id: '/self',
  path: '/self',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOcrReviewRoute = DashboardOcrReviewRouteImport.update({
  id: '/ocr-review',
  path: '/ocr-review',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGateRoute = DashboardGateRouteImport.update({
  id: '/gate',
  path: '/gate',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDockRoute = DashboardDockRouteImport.update({
  id: '/dock',
  path: '/dock',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiopsRoute = DashboardAiopsRouteImport.update({
  id: '/aiops',
  path: '/aiops',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutTokenRoute = CheckoutTokenRouteImport.update({
  id: '/checkout/$token',
  path: '/checkout/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinTokenRoute = CheckinTokenRouteImport.update({
  id: '/checkin/$token',
  path: '/checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/aiops': typeof DashboardAiopsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/dock': typeof DashboardDockRoute
  '/dashboard/gate': typeof DashboardGateRoute
  '/dashboard/ocr-review': typeof DashboardOcrReviewRoute
  '/dashboard/self': typeof DashboardSelfRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/weighbridge': typeof DashboardWeighbridgeRoute
  '/dashboard/yard': typeof DashboardYardRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/aiops': typeof DashboardAiopsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/dock': typeof DashboardDockRoute
  '/dashboard/gate': typeof DashboardGateRoute
  '/dashboard/ocr-review': typeof DashboardOcrReviewRoute
  '/dashboard/self': typeof DashboardSelfRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/weighbridge': typeof DashboardWeighbridgeRoute
  '/dashboard/yard': typeof DashboardYardRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/aiops': typeof DashboardAiopsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/dock': typeof DashboardDockRoute
  '/dashboard/gate': typeof DashboardGateRoute
  '/dashboard/ocr-review': typeof DashboardOcrReviewRoute
  '/dashboard/self': typeof DashboardSelfRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/weighbridge': typeof DashboardWeighbridgeRoute
  '/dashboard/yard': typeof DashboardYardRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/checkin/$token'
    | '/checkout/$token'
    | '/dashboard/admin'
    | '/dashboard/aiops'
    | '/dashboard/analytics'
    | '/dashboard/dock'
    | '/dashboard/gate'
    | '/dashboard/ocr-review'
    | '/dashboard/self'
    | '/dashboard/tasks'
    | '/dashboard/weighbridge'
    | '/dashboard/yard'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/checkin/$token'
    | '/checkout/$token'
    | '/dashboard/admin'
    | '/dashboard/aiops'
    | '/dashboard/analytics'
    | '/dashboard/dock'
    | '/dashboard/gate'
    | '/dashboard/ocr-review'
    | '/dashboard/self'
    | '/dashboard/tasks'
    | '/dashboard/weighbridge'
    | '/dashboard/yard'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/checkin/$token'
    | '/checkout/$token'
    | '/dashboard/admin'
    | '/dashboard/aiops'
    | '/dashboard/analytics'
    | '/dashboard/dock'
    | '/dashboard/gate'
    | '/dashboard/ocr-review'
    | '/dashboard/self'
    | '/dashboard/tasks'
    | '/dashboard/weighbridge'
    | '/dashboard/yard'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  CheckinTokenRoute: typeof CheckinTokenRoute
  CheckoutTokenRoute: typeof CheckoutTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/yard': {
      id: '/dashboard/yard'
      path: '/yard'
      fullPath: '/dashboard/yard'
      preLoaderRoute: typeof DashboardYardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/weighbridge': {
      id: '/dashboard/weighbridge'
      path: '/weighbridge'
      fullPath: '/dashboard/weighbridge'
      preLoaderRoute: typeof DashboardWeighbridgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/self': {
      id: '/dashboard/self'
      path: '/self'
      fullPath: '/dashboard/self'
      preLoaderRoute: typeof DashboardSelfRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ocr-review': {
      id: '/dashboard/ocr-review'
      path: '/ocr-review'
      fullPath: '/dashboard/ocr-review'
      preLoaderRoute: typeof DashboardOcrReviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gate': {
      id: '/dashboard/gate'
      path: '/gate'
      fullPath: '/dashboard/gate'
      preLoaderRoute: typeof DashboardGateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dock': {
      id: '/dashboard/dock'
      path: '/dock'
      fullPath: '/dashboard/dock'
      preLoaderRoute: typeof DashboardDockRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/aiops': {
      id: '/dashboard/aiops'
      path: '/aiops'
      fullPath: '/dashboard/aiops'
      preLoaderRoute: typeof DashboardAiopsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/$token': {
      id: '/checkout/$token'
      path: '/checkout/$token'
      fullPath: '/checkout/$token'
      preLoaderRoute: typeof CheckoutTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$token': {
      id: '/checkin/$token'
      path: '/checkin/$token'
      fullPath: '/checkin/$token'
      preLoaderRoute: typeof CheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAiopsRoute: typeof DashboardAiopsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardDockRoute: typeof DashboardDockRoute
  DashboardGateRoute: typeof DashboardGateRoute
  DashboardOcrReviewRoute: typeof DashboardOcrReviewRoute
  DashboardSelfRoute: typeof DashboardSelfRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardWeighbridgeRoute: typeof DashboardWeighbridgeRoute
  DashboardYardRoute: typeof DashboardYardRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAiopsRoute: DashboardAiopsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardDockRoute: DashboardDockRoute,
  DashboardGateRoute: DashboardGateRoute,
  DashboardOcrReviewRoute: DashboardOcrReviewRoute,
  DashboardSelfRoute: DashboardSelfRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardWeighbridgeRoute: DashboardWeighbridgeRoute,
  DashboardYardRoute: DashboardYardRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  CheckinTokenRoute: CheckinTokenRoute,
  CheckoutTokenRoute: CheckoutTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
